//This file is automatically generated, please do not modify it manually

using System.Collections.Generic;

namespace Config
{
	public partial class Text2
	{
		/// <summary>t0</summary>
		public int t0;

		/// <summary>t1</summary>
		public string t1;

		/// <summary>t2</summary>
		public int[] t2;

		/// <summary>t3</summary>
		public string[] t3;

		/// <summary>t4</summary>
		public string[][] t4;

		/// <summary>t5</summary>
		public bool t5;

		/// <summary>t6</summary>
		public float t6;

		/// <summary>t7</summary>
		public double t7;
	}
}
